-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 15:28:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InduApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `InduApp` ;

-- -----------------------------------------------------
-- Schema InduApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InduApp` DEFAULT CHARACTER SET utf8 ;
USE `InduApp` ;

-- -----------------------------------------------------
-- Table `InduApp`.`Guia_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Guia_proyecto` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Guia_proyecto` (
  `id_guia_proyecto` INT NOT NULL AUTO_INCREMENT,
  `codigo_guia_proyecto` VARCHAR(45) NULL,
  `nombre_proyecto` VARCHAR(105) NULL,
  `responsable_proyecto` VARCHAR(45) NULL,
  `tipo_guia` ENUM("proyecto", "otro") NULL,
  PRIMARY KEY (`id_guia_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Producto` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_pruducto` VARCHAR(200) NOT NULL,
  `idioma_producto` ENUM("ingles", "español", "frances", "otro") NULL,
  `subtipo_producto` VARCHAR(600) NULL,
  `tipo_producto` VARCHAR(500) NULL,
  `anio_producto` YEAR NULL,
  `id_Guia` INT NOT NULL,
  `id_linea_programatica` INT NOT NULL,
  PRIMARY KEY (`id_Producto`),
  INDEX `fk_Producto_Guia1_idx` (`id_Guia` ASC) VISIBLE,
  INDEX `fk_Producto_linea_programatica1_idx` (`id_linea_programatica` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Guia1`
    FOREIGN KEY (`id_Guia`)
    REFERENCES `InduApp`.`Guia_proyecto` (`id_guia_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_linea_programatica1`
    FOREIGN KEY (`id_linea_programatica`)
    REFERENCES `InduApp`.`linea_programatica` (`id_linea_programatica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`Producto_has_Semillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Producto_has_Semillero` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Producto_has_Semillero` (
  `Producto_id_Producto` INT NOT NULL,
  `Semillero_id_Semillero` INT NOT NULL,
  PRIMARY KEY (`Producto_id_Producto`, `Semillero_id_Semillero`),
  INDEX `fk_Producto_has_Semillero_Semillero1_idx` (`Semillero_id_Semillero` ASC) VISIBLE,
  INDEX `fk_Producto_has_Semillero_Producto1_idx` (`Producto_id_Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Semillero_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `InduApp`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Semillero_Semillero1`
    FOREIGN KEY (`Semillero_id_Semillero`)
    REFERENCES `InduApp`.`Semillero` (`id_Semillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`Semillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Semillero` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Semillero` (
  `id_Semillero` INT NOT NULL AUTO_INCREMENT,
  `nombre_semillero` VARCHAR(105) NULL,
  `lider_semillero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Semillero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL,
  `apellido_usuario` VARCHAR(45) NULL,
  `correo_usuario` VARCHAR(45) NULL,
  `contrasena_usuario` VARCHAR(45) NULL,
  `telefono_usuario` VARCHAR(20) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`Uusario_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`Uusario_has_roles` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`Uusario_has_roles` (
  `Uusario_id_usuario` INT NOT NULL,
  `roles_id_Roles` INT NOT NULL,
  PRIMARY KEY (`Uusario_id_usuario`, `roles_id_Roles`),
  INDEX `fk_Uusario_has_roles_roles1_idx` (`roles_id_Roles` ASC) VISIBLE,
  INDEX `fk_Uusario_has_roles_Uusario1_idx` (`Uusario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Uusario_has_roles_Uusario1`
    FOREIGN KEY (`Uusario_id_usuario`)
    REFERENCES `InduApp`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uusario_has_roles_roles1`
    FOREIGN KEY (`roles_id_Roles`)
    REFERENCES `InduApp`.`roles` (`id_Roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`linea_programatica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`linea_programatica` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`linea_programatica` (
  `id_linea_programatica` INT NOT NULL AUTO_INCREMENT,
  `nombre_linea_programatica` VARCHAR(500) NULL,
  PRIMARY KEY (`id_linea_programatica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`roles` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`roles` (
  `id_Roles` INT NOT NULL AUTO_INCREMENT,
  `tipo_Rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InduApp`.`usuarios_has_Guia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InduApp`.`usuarios_has_Guia` ;

CREATE TABLE IF NOT EXISTS `InduApp`.`usuarios_has_Guia` (
  `id_usuarios` INT NOT NULL,
  `id_Guia` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`, `id_Guia`),
  INDEX `fk_Funcionario_has_Guia_Guia1_idx` (`id_Guia` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Guia_Funcionario1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_has_Guia_Funcionario1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `InduApp`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Guia_Guia1`
    FOREIGN KEY (`id_Guia`)
    REFERENCES `InduApp`.`Guia_proyecto` (`id_guia_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
